spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polixia_db_v4.7.8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: application-service
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
hystrix:
  timeout: 10000
app:
 version: "@project.version@"
 build-time-stamp: "@timestamp@"
