from java:8
expose 8080
add /target/polixia-settings-service-1.2.0-SNAPSHOT.jar /opt/polixia-settings-service-1.2.0-SNAPSHOT.jar
workdir /opt
entrypoint ["java","-jar","polixia-settings-service-1.2.0-SNAPSHOT.jar"]

