from java:8
expose 8080
add /target/application-service-0.0.1-SNAPSHOT.jar /opt/application-service-0.0.1-SNAPSHOT.jar
workdir /opt
entrypoint ["java","-jar","application-service-0.0.1-SNAPSHOT.jar"]

