spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polixia_pi_db
    username: pserviceuser
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: settings-server
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080


app:
 version: "@project.version@"
 build-time-stamp: "@timestamp@"

